FROM tomcat:8.0.51-jre8-alpine
MAINTAINER chougalerohit73@.com
# copy war file on to container
COPY ./target/traveller-ms*.jar /usr/local/tomcat/webapps
EXPOSE  8080
USER traveller-ms
WORKDIR /usr/local/tomcat/webapps
CMD ["catalina.sh","run"]